export const KEYS = {
  TOKEN: "TOKEN",
  REMEMBER: "REMEMBER",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  QUESTION_BANK: "QUESTION_BANK",
  QUESTION_ESSAY : "QUESTION_ESSAY",
  QUESTION_QUIZ : "QUESTION_QUIZ",
};
